spring.application.name=pedidos

# Configuracoes de ligacao ao MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_estoque_pedidos?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


springdoc.hateoas.enabled=true
springdoc.packages-to-scan=com.estoque.pedidos

spring.cache.type=caffeine
#Limita a 1000 itens e expira os dados 10 minutos apos serem salvos
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m